[general]
SUPABASE_URL = "https://rthlzkdzfnpzrmwdkpxm.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0aGx6a2R6Zm5wenJtd2RrcHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1NjAwNDAsImV4cCI6MjA4MTEzNjA0MH0.AG3tipsbsMLf5asRRbnKwyuFIUOcbJFnBPkBUQxqgZI"